// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Rl87Bh4cyLYMPXIzf8dxRk-9ltN2fFw',
    appId: '1:1061760279132:web:856c85c97b7ea5a968fc99',
    messagingSenderId: '1061760279132',
    projectId: 'izcfinance',
    authDomain: 'izcfinance.firebaseapp.com',
    storageBucket: 'izcfinance.firebasestorage.app',
    measurementId: 'G-BERDBNF38X',
    databaseURL: 'https://izcfinance-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA610yoLEJBP5S3H8Vjvy4u1WAKnu2247g',
    appId: '1:1061760279132:android:8c17c041a3f344b468fc99',
    messagingSenderId: '1061760279132',
    projectId: 'izcfinance',
    storageBucket: 'izcfinance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvgNrheYlFT0ZsUaxY4WDdTT-X3OQfm2E',
    appId: '1:1061760279132:ios:0de9ba9da235984768fc99',
    messagingSenderId: '1061760279132',
    projectId: 'izcfinance',
    storageBucket: 'izcfinance.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvgNrheYlFT0ZsUaxY4WDdTT-X3OQfm2E',
    appId: '1:1061760279132:ios:0de9ba9da235984768fc99',
    messagingSenderId: '1061760279132',
    projectId: 'izcfinance',
    storageBucket: 'izcfinance.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Rl87Bh4cyLYMPXIzf8dxRk-9ltN2fFw',
    appId: '1:1061760279132:web:6a841f7611ab8ecb68fc99',
    messagingSenderId: '1061760279132',
    projectId: 'izcfinance',
    authDomain: 'izcfinance.firebaseapp.com',
    storageBucket: 'izcfinance.firebasestorage.app',
    measurementId: 'G-H8YJ909SJX',
  );
}
